---
version: 5.8.0
slug: configurator
name: File editor
description: Simple browser-based file editor for Home Assistant
url: https://github.com/home-assistant/addons/tree/master/configurator
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 0.91.1
homeassistant_api: true
image: homeassistant/{arch}-addon-configurator
ingress: true
init: false
map:
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  dirsfirst: false
  enforce_basepath: true
  git: true
  ignore_pattern:
    - __pycache__
    - .cloud
    - .storage
    - deps
  ssh_keys: []
panel_icon: mdi:wrench
schema:
  dirsfirst: bool
  enforce_basepath: bool
  git: bool
  ignore_pattern:
    - str
  ssh_keys:
    - str
    envisalink:
  host: 192.168.1.200
  panel_type: DSC
  user_name: user       
  password: user         
  code: '8913'           
  port: 4025
  evl_version: 4
  zones:
    1:
      name: "Κύρια είσοδος & μπαλκονόπορτα σαλόνι"
    2:
      name: "Ραντάρ σαλόνι"
    3:
      name: "Ραντάρ κουζίνας"
    4:
      name: "Πόρτα κουζίνας"
    5:
      name: "Μπαλκονόπορτα κουζίνας"
    6:
      name: "Πατζούρι κουζίνας"
    7:
      name: "Πατζουράκι κουζίνας"
    8:
      name: "Μπαλκονόπορτα δωματίων 1-2"
    9:
      name: "Πατζούρι δωματίων 1-2"
    10:
      name: "Μπαλκονόπορτα μάστερ/γραφείο/τραπεζαρία"
    11:
      name: "Πατζούρια μάστερ/γραφείο/τραπεζαρία"
    12:
      name: "Πατζούρι σαλονιού"
    13:
      name: "Ραντάρ μάστερ"
    14:
      name: "Ραντάρ γραφείο"
    15:
      name: "Ραντάρ δωμάτιο 1"
    16:
      name: "Ραντάρ δωμάτιο 2"
    17:
      name: "Προστασία σειρήνας"
  partitions:
    1:
      name: "Κεντρικός Συναγερμός"
